name: "Bump project version"
description: "Bumps version mentioned in specific list of files"
author: "Eugen Ciur <eugen@papermerge.com>"
inputs:
  files_list:
    description: "List of files, delimited by comma, with source version"
    default: "pyproject.toml"
  incremented_part:
    description: "Which part of the version to increment"
    default: "micro"
outputs:
  old_version:
    description: "Project's version before the increment"
  new_version:
    description: "Project's version after the increment"
runs:
  using: "docker"
  image: "Dockerfile"
